/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: yankobe (https://sketchfab.com/yankobe.do)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cyber-supercar-286d87fb435448e3bc05806f52967307
Title: Cyber Supercar
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from '@react-three/fiber';
import { a } from '@react-spring/three';

import cybercarScene from '../assets/3d/cyber_car.glb';

const CyberCar = (props) => {
  const { nodes, materials } = useGLTF(cybercarScene);
  const carRef = useRef();

  return (
    <a.group ref={carRef} {...props} >
      <group scale={0.01}>
        <primitive object={nodes._rootJoint} />
        <skinnedMesh
          geometry={nodes.Object_5.geometry}
          material={materials.CS_Body_02}
          skeleton={nodes.Object_5.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_6.geometry}
          material={materials.CS_Windshield}
          skeleton={nodes.Object_6.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_7.geometry}
          material={materials.CS_Body_02_Glass}
          skeleton={nodes.Object_7.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_8.geometry}
          material={materials.CS_Body_01}
          skeleton={nodes.Object_8.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_9.geometry}
          material={materials.CS_Chassis}
          skeleton={nodes.Object_9.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_10.geometry}
          material={materials.CS_Interior}
          skeleton={nodes.Object_10.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_11.geometry}
          material={materials.CS_Seats}
          skeleton={nodes.Object_11.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_12.geometry}
          material={materials.CS_Wheels}
          skeleton={nodes.Object_12.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Object_13.geometry}
          material={materials.CS_Wheels}
          skeleton={nodes.Object_13.skeleton}
        />
      </group>
    </a.group>
  );
}

export default CyberCar;