/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: eduterrataca (https://sketchfab.com/eduterrataca)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/004-chess-rook-53ca0316e8794e5a83f3a20532a3e13a
Title: 004 Chess Rook
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from '@react-three/fiber';
import { a } from '@react-spring/three';

const Pawn = (props) => {
  const pawnRef = useRef();
  const pawnScene = '/assets/3d/chess_pawn.glb';
  const { nodes, materials } = useGLTF(pawnScene);

  return (
    <a.group ref={personRef} {...props}>
      <group name="Sketchfab_Scene">
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials["Scene_-_Root"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.212}
      />
      </group>
    </a.group>
  );
}

export default Pawn;

