/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Decentralized (https://sketchfab.com/decentralized13)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/biden-twist-dance-d53b0d543231453998ff5ea68f7a45a3
Title: Biden Twist Dance
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from '@react-three/fiber';
import { a } from '@react-spring/three';

const Person = (props) => {
  const personRef = useRef();
  const personScene = '/assets/3d/person.glb';
  const { nodes, materials } = useGLTF(personScene);

  return (
    <a.group ref={personRef} {...props}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.838}
        >
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="AvatarRoot1_0">
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <skinnedMesh
                    name="Object_81"
                    geometry={nodes.Object_81.geometry}
                    material={materials.material_0}
                    skeleton={nodes.Object_81.skeleton}
                  />
                  <skinnedMesh
                    name="Object_84"
                    geometry={nodes.Object_84.geometry}
                    material={materials.material_1}
                    skeleton={nodes.Object_84.skeleton}
                  />
                  <skinnedMesh
                    name="Object_87"
                    geometry={nodes.Object_87.geometry}
                    material={materials.material_2}
                    skeleton={nodes.Object_87.skeleton}
                  />
                  <skinnedMesh
                    name="Object_90"
                    geometry={nodes.Object_90.geometry}
                    material={materials.material_3}
                    skeleton={nodes.Object_90.skeleton}
                  />
                  <skinnedMesh
                    name="Object_93"
                    geometry={nodes.Object_93.geometry}
                    material={materials.material_4}
                    skeleton={nodes.Object_93.skeleton}
                  />
                  <skinnedMesh
                    name="Object_96"
                    geometry={nodes.Object_96.geometry}
                    material={materials.material_5}
                    skeleton={nodes.Object_96.skeleton}
                  />
                  <skinnedMesh
                    name="Object_99"
                    geometry={nodes.Object_99.geometry}
                    material={materials.material_6}
                    skeleton={nodes.Object_99.skeleton}
                  />
                  <skinnedMesh
                    name="Object_102"
                    geometry={nodes.Object_102.geometry}
                    material={materials.material_7}
                    skeleton={nodes.Object_102.skeleton}
                  />
                  <skinnedMesh
                    name="Object_105"
                    geometry={nodes.Object_105.geometry}
                    material={materials.material_8}
                    skeleton={nodes.Object_105.skeleton}
                  />
                  <skinnedMesh
                    name="Object_108"
                    geometry={nodes.Object_108.geometry}
                    material={materials.material_9}
                    skeleton={nodes.Object_108.skeleton}
                  />
                  <skinnedMesh
                    name="Object_109"
                    geometry={nodes.Object_109.geometry}
                    material={materials.material_9}
                    skeleton={nodes.Object_109.skeleton}
                  />
                  <group name="_75_correction">
                    <group name="_75" />
                  </group>
                  <group name="_77_correction">
                    <group name="_77" />
                  </group>
                  <group name="_79_correction">
                    <group name="_79" />
                  </group>
                  <group name="_81_correction">
                    <group name="_81" />
                  </group>
                  <group name="_83_correction">
                    <group name="_83" />
                  </group>
                  <group name="_85_correction">
                    <group name="_85" />
                  </group>
                  <group name="_87_correction">
                    <group name="_87" />
                  </group>
                  <group name="_89_correction">
                    <group name="_89" />
                  </group>
                  <group name="_91_correction">
                    <group name="_91" />
                  </group>
                  <group name="_93_correction">
                    <group name="_93" />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </a.group>
  );
}

export default Person;