/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: DJHaski (https://sketchfab.com/djhaski)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pizza-model-c0b338ca475d4147bfba00b071e0cbd9
Title: Pizza Model
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/pizza_model.glb");
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder35_blinn4_0.geometry}
          material={materials.blinn4}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder35_blinn3_0.geometry}
          material={materials.blinn3}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder35_blinn13_0.geometry}
          material={materials.blinn13}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder35_blinn1_0.geometry}
          material={materials.blinn1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder35_blinn2_0.geometry}
          material={materials.blinn2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder35_blinn2_0_1.geometry}
          material={materials.blinn2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder35_blinn12_0.geometry}
          material={materials.blinn12}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder35_blinn6_0.geometry}
          material={materials.blinn6}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder35_blinn8_0.geometry}
          material={materials.blinn8}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder35_blinn10_0.geometry}
          material={materials.blinn10}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder35_blinn7_0.geometry}
          material={materials.blinn7}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder35_blinn9_0.geometry}
          material={materials.blinn9}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.pCylinder35_blinn11_0.geometry}
          material={materials.blinn11}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/pizza_model.glb");


rembrandt

city
Made by @NikkitaFTW & contributors inspired by the gltfjsx cli

