/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Giimann (https://sketchfab.com/giimann)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/alien-terrain-05-hdri-7ba0da88576d4f4592beaaa0e9e3ff2d
Title: Alien Terrain 05 HDRI
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { a } from "@react-spring/three";

const AlienPlanet = (props) => {
  const alienPlanetRef = useRef();
  const { nodes, materials } = useGLTF("/assets/3d/alien_planet.glb");

  return (
    <a.group ref={alienPlanetRef} {...props}>
      <mesh
        geometry={nodes.pack1_Background_0.geometry}
        material={materials.Background}
        scale={0.01}
      />
    </a.group>
  );
};

export default AlienPlanet;
