/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Wen Yeh (https://sketchfab.com/wenyeh1110)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/bird-orange-0d31748606c2499fb652c0c1052b7cfa
Title: Bird Orange
*/


import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from '@react-three/fiber';
import { a } from '@react-spring/three';

const OrangeBird = (props) => {
  const birdOrangeRef = useRef();
  const birdOrangeScene = '/assets/3d/bird_orange.glb';
  const { nodes, materials } = useGLTF(birdOrangeScene);

  return (
    <a.group ref={birdOrangeRef} {...props}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={46.683}
        >
          <group
            name="bfb1ea86655f4c4ab4c6cbbb449cedf4fbx"
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group name="BirdOrange_all">
                  <group
                    name="Main"
                    position={[-0.083, 0, 0.451]}
                    rotation={[0, -0.074, 0]}
                  >
                    <group name="Object_6">
                      <primitive object={nodes._rootJoint} />
                      <skinnedMesh
                        name="Object_51"
                        geometry={nodes.Object_51.geometry}
                        material={materials.BirdOrange_LMB}
                        skeleton={nodes.Object_51.skeleton}
                      />
                      <group name="Object_50" />
                    </group>
                  </group>
                  <group name="Geometry">
                    <group name="BirdOrange" />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </a.group>
  );
}

export default OrangeBird;



