/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: eduterrataca (https://sketchfab.com/eduterrataca)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/004-chess-rook-53ca0316e8794e5a83f3a20532a3e13a
Title: 004 Chess Rook
*/


import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from '@react-three/fiber';
import { a } from '@react-spring/three';

const Rook = (props) => {
  const rookRef = useRef();
  const rookScene = '/assets/3d/004_chess_rook.glb';
  const { nodes, materials } = useGLTF(rookScene);

  return (
    <a.group ref={personRef} {...props}>
      <group name="Sketchfab_Scene">
        <group scale={0.01}>
          <mesh
          geometry={nodes.Torre000_Peca_0.geometry}
          material={materials.Peca}
        />
        </group>
      </group>
    </a.group>
  );
}
export default Rook;