/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Inditrion Dradnon (https://sketchfab.com/dradnon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/freeport-space-station-2-709bb1fee20242d4aa56f40f017955d7
Title: Freeport Space Station 2
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { a } from "@react-spring/three";

const SpaceStation = (props) => {
  const spaceStationRef = useRef();
  const { nodes, materials } = useGLTF("/assets/3d/space_station.glb");

  return (
    <a.group ref={spaceStationRef} {...props}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[-29.227, -5.102, -36.785]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[1, 1, 0.569]}
          >
            <mesh
              geometry={nodes.MaterialFBXASC032FBXASC0352142150880.geometry}
              material={materials.MaterialFBXASC032FBXASC0352142150880}
            />
            <mesh
              geometry={nodes.MaterialFBXASC032FBXASC0352142150880_1.geometry}
              material={materials.MaterialFBXASC032FBXASC0352142150880}
            />
            <mesh
              geometry={nodes.MaterialFBXASC032FBXASC0352142150880_2.geometry}
              material={materials.MaterialFBXASC032FBXASC0352142150880}
            />
            <mesh
              geometry={nodes["SG-Engine"].geometry}
              material={materials["SG-Engine"]}
            />
            <mesh
              geometry={nodes.MaterialFBXASC032FBXASC0352142167703.geometry}
              material={materials.MaterialFBXASC032FBXASC0352142167703}
            />
            <mesh
              geometry={nodes.MaterialFBXASC032FBXASC0352142167704.geometry}
              material={materials.MaterialFBXASC032FBXASC0352142167704}
            />
            <mesh
              geometry={nodes["SG-Gold-glow"].geometry}
              material={materials["SG-Gold-glow"]}
            />
            <mesh
              geometry={nodes["SG-Window"].geometry}
              material={materials["SG-Window"]}
            />
            <mesh
              geometry={nodes.Window.geometry}
              material={materials.Window}
            />
            <mesh
              geometry={nodes.ORDNUNGSKRAFTFBXASC032Graviton.geometry}
              material={materials.ORDNUNGSKRAFTFBXASC032Graviton}
            />
            <mesh
              geometry={nodes["SG-LightW"].geometry}
              material={materials["SG-LightW"]}
            />
          </group>
          <group
            position={[-30.055, 9.498, -38.299]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.373}
          >
            <mesh
              geometry={nodes.MaterialFBXASC032FBXASC0352142150880_3.geometry}
              material={materials.MaterialFBXASC032FBXASC0352142150880}
            />
            <mesh
              geometry={nodes.MaterialFBXASC032FBXASC0352142150880_4.geometry}
              material={materials.MaterialFBXASC032FBXASC0352142150880}
            />
            <mesh
              geometry={nodes.MaterialFBXASC032FBXASC0352142150880_5.geometry}
              material={materials.MaterialFBXASC032FBXASC0352142150880}
            />
            <mesh
              geometry={nodes.MaterialFBXASC032FBXASC0352142150880_6.geometry}
              material={materials.MaterialFBXASC032FBXASC0352142150880}
            />
            <mesh
              geometry={nodes.MaterialFBXASC032FBXASC0352142150880_7.geometry}
              material={materials.MaterialFBXASC032FBXASC0352142150880}
            />
            <mesh
              geometry={nodes.MaterialFBXASC032FBXASC0352142150880_8.geometry}
              material={materials.MaterialFBXASC032FBXASC0352142150880}
            />
            <mesh
              geometry={nodes.MaterialFBXASC032FBXASC0352142150880_9.geometry}
              material={materials.MaterialFBXASC032FBXASC0352142150880}
            />
            <mesh
              geometry={nodes.MaterialFBXASC032FBXASC0352142150880_10.geometry}
              material={materials.MaterialFBXASC032FBXASC0352142150880}
            />
            <mesh
              geometry={nodes.MaterialFBXASC032FBXASC0352142150880_11.geometry}
              material={materials.MaterialFBXASC032FBXASC0352142150880}
            />
            <mesh
              geometry={nodes.MaterialFBXASC032FBXASC0352142150880_12.geometry}
              material={materials.MaterialFBXASC032FBXASC0352142150880}
            />
            <mesh
              geometry={nodes.MaterialFBXASC032FBXASC0352142150880_13.geometry}
              material={materials.MaterialFBXASC032FBXASC0352142150880}
            />
            <mesh
              geometry={nodes.MaterialFBXASC032FBXASC0352142150880_14.geometry}
              material={materials.MaterialFBXASC032FBXASC0352142150880}
            />
            <mesh
              geometry={nodes.MaterialFBXASC032FBXASC0352142150880_15.geometry}
              material={materials.MaterialFBXASC032FBXASC0352142150880}
            />
            <mesh
              geometry={nodes.MaterialFBXASC032FBXASC0352142150880_16.geometry}
              material={materials.MaterialFBXASC032FBXASC0352142150880}
            />
            <mesh
              geometry={nodes.MaterialFBXASC032FBXASC0352142150880_17.geometry}
              material={materials.MaterialFBXASC032FBXASC0352142150880}
            />
            <mesh
              geometry={nodes["SG-Gold-glow_1"].geometry}
              material={materials["SG-Gold-glow"]}
            />
            <mesh
              geometry={nodes.Window_1.geometry}
              material={materials.Window}
            />
            <mesh
              geometry={nodes.Window_2.geometry}
              material={materials.Window}
            />
            <mesh
              geometry={nodes.Window_3.geometry}
              material={materials.Window}
            />
          </group>
        </group>
      </group>
    </a.group>
  );
};

export default SpaceStation;
