/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Giimann (https://sketchfab.com/giimann)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/winter-terrain-02-67a63b4b18b5463687a91ac346aac752
Title: Winter Terrain 02
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { a } from "@react-spring/three";

const WinterTerrain = (props) => {
  const winterTerrainRef = useRef();
  const { nodes, materials } = useGLTF("/assets/3d/winter_terrain.glb");
  return (
    <a.group ref={winterTerrainRef} {...props}>
      <mesh
        geometry={nodes.Fairytale_Garden_Background_0.geometry}
        material={materials.Background}
        scale={0.01}
      />
    </a.group>
  );
};

export default WinterTerrain;
